image:
  - Visual Studio 2017
  - Visual Studio 2019
platform:
  - x64
  - x86
configuration:
  - Debug
  - Release
clone_folder: c:\projects\alx_unique_ptr
before_build:
  - cmd: cd c:\projects\alx_unique_ptr
  - cmd: mkdir build
  - cmd: cd build
  - cmd: cmake .. -DBUILD_TESTING=On
build:
  project: c:\projects\alx_unique_ptr\build\alx_unique_ptr.sln
  parallel: true
install:
  - cmd: set PATH=%PATH%;%PYTHON%/Scripts/
  - cmd: pip.exe install conan
  - cmd: cd ..
  - cmd: conan user
  - cmd: conan --version
  - cmd: conan remote add bincrafters https://api.bintray.com/conan/bincrafters/public-conan
  - cmd: cd c:\projects\alx_unique_ptr
test_script:
  - cmd: c:\projects\alx_unique_ptr\build\bin\alx_unique_ptr_tests.exe
matrix:
  - fast_finish: true
for:
  -
    matrix:
    platform: x64
    before_build:
      - cmd: cmake .. -A x64 -DBUILD_TESTING=On
  -
    matrix:
    platform: x86
    before_build:
      - cmd: cmake .. -A Win32 -DBUILD_TESTING=On